### PR TITLE
Fix NullReferenceException when deregistering a builder with a custom matcher

### LINKED ISSUE #361: NullReferenceException when Deregister builder with a custom matcher
Hi Martin,

Deregister a builder from `HttpClientInterceptorOptions` object has not work correctly. This edge case has occurred when a custom matcher was added to a builder and then tried to deregister it from options.

This exception is raised because it should be configured matcher before calling `buildKey` in the `Deregister` method.

Here is a sample scenario for this bug:

```C#
var builder = new HttpRequestInterceptionBuilder()
    .Requests().For(async (request) => await Task.FromResult(true));

var options = new HttpClientInterceptorOptions()
    .Register(builder);

options.Deregister(builder); // NullReferenceException is raised
```

### PR DESCRIPTION
**Pull request by martincostello**
Fix `NullReferenceException` deregistering a builder if it used a custom match delegate.

Now it will deregister as long as it hasn't been mutated (otherwise it is "lost" and can't be removed).

If the registration is "lost", then an `InvalidOperationException` is thrown instead to draw the caller's attention to the fact their code is not behaving as expected. Similarly, an exception is now thrown if trying to deregister an HTTP request/builder that was never registered.

Resolves #361.

### CODE REVIEW

File: src/HttpClientInterception/HttpClientInterceptorOptions.cs [hunk 1]
```diff
@@ -315,7 +329,11 @@ public HttpClientInterceptorOptions Register(HttpRequestInterceptionBuilder buil
 
         HttpInterceptionResponse interceptor = builder.Build();
 
-        ConfigureMatcherAndRegister(interceptor);
+        string key = ConfigureMatcherAndRegister(interceptor);
+
+        // Store the key so deregistration for the builder works if
```
Comment (RhokoCy) [inline src/HttpClientInterception/HttpClientInterceptorOptions.cs:334]:
```suggestion
        // Store the key so deregistration for the builder works,
```

**Review by RhokoCy — APPROVED** [review]
